name: Build

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: self-hosted
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3